# Generated by Django 5.1.1 on 2024-11-04 01:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('type_acheteur', models.CharField(max_length=200, null=True)),
                ('numero_cni', models.CharField(max_length=200, null=True)),
                ('numero_oncc', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('filiale', models.CharField(max_length=200, null=True)),
                ('coordonnees_geographiques', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'acheteur',
                'verbose_name_plural': 'acheteurs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(null=True)),
                ('type_cooperative', models.CharField(max_length=200, null=True)),
                ('siege_social', models.CharField(max_length=200, null=True)),
                ('nom_responssable', models.CharField(max_length=200, null=True)),
                ('contact_responssable', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('departement', models.CharField(max_length=200, null=True)),
                ('arrondissement', models.CharField(max_length=200, null=True)),
                ('village', models.CharField(max_length=200, null=True)),
                ('coordonnees_gps', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Cooperative',
                'verbose_name_plural': 'Cooperatives',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_de_passe', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifiant', models.CharField(max_length=500, null=True)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('date_naissance', models.CharField(max_length=200, null=True)),
                ('lieu_naissance', models.CharField(max_length=200, null=True)),
                ('genre', models.CharField(max_length=200, null=True)),
                ('numero_cni', models.CharField(max_length=200, null=True)),
                ('identifiant_fodecc_cicc', models.CharField(max_length=200, null=True)),
                ('numero_telephone', models.CharField(max_length=200, null=True)),
                ('tel_second', models.CharField(max_length=200, null=True)),
                ('an_enreg', models.CharField(max_length=200, null=True)),
                ('nom_cooperative', models.CharField(max_length=200, null=True)),
                ('autre_cooperative', models.CharField(max_length=200, null=True)),
                ('residence', models.CharField(max_length=200, null=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProducteurCooperative', to='cocoaApp.cooperative')),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_titre_foncier', models.CharField(max_length=200, null=True)),
                ('statut', models.CharField(max_length=200, null=True)),
                ('identifiant', models.CharField(max_length=200, null=True)),
                ('superficie', models.FloatField(null=True)),
                ('nombre_arbres', models.IntegerField(null=True)),
                ('age_moyen_arbres', models.FloatField(null=True)),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('id_producteur', models.CharField(max_length=200, null=True)),
                ('type_culture', models.CharField(max_length=200, null=True, verbose_name='Type_culture')),
                ('an_creation', models.FloatField(null=True)),
                ('arrondisement', models.CharField(max_length=200, null=True)),
                ('departement', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('longueur', models.FloatField(null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('village', models.CharField(max_length=200, null=True)),
                ('voie_eau', models.CharField(max_length=200, null=True)),
                ('url', models.TextField()),
                ('url_carte', models.CharField(max_length=200, null=True)),
                ('producteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelleProducteur', to='cocoaApp.producteur')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
            },
        ),
        migrations.CreateModel(
            name='CooperativeProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arriver_producteur', models.DateField()),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooperativeProd', to='cocoaApp.cooperative')),
                ('producteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producteurCoop', to='cocoaApp.producteur')),
            ],
            options={
                'verbose_name': 'CooperativeProducteur',
                'verbose_name_plural': 'CooperativeProducteurs',
            },
        ),
        migrations.CreateModel(
            name='Sac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_qr', models.ImageField(max_length=200, null=True, upload_to='images/')),
                ('quantite', models.FloatField(null=True)),
                ('date_creation', models.DateField(null=True)),
                ('date_modification', models.DateField(null=True)),
                ('acheteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acheteur', to='cocoaApp.acheteur')),
            ],
            options={
                'verbose_name': 'Sac',
                'verbose_name_plural': 'Sacs',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=200, null=True)),
                ('quantite', models.FloatField()),
                ('type_commercial', models.CharField(max_length=200, null=True)),
                ('urlParcelle', models.CharField(max_length=200, null=True)),
                ('url_carte', models.CharField(max_length=200, null=True)),
                ('taux_humidite', models.FloatField(null=True)),
                ('date_recolt', models.DateField(null=True)),
                ('date_livraison', models.DateField(null=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotCooperative', to='cocoaApp.cooperative')),
                ('parcelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotParcelle', to='cocoaApp.parcelle')),
                ('producteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotProducteur', to='cocoaApp.producteur')),
                ('sac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotSac', to='cocoaApp.sac')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
            },
        ),
    ]
