# Generated by Django 5.1.1 on 2024-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
